data:
  training_csv: data/training_combined.csv  # Combined EU traits + EIVE per species
  prediction_csv: data/non_eu_traits.csv    # Traits for non‑EU species
  id_columns: [Species, Genus, Family]
  categorical_traits: [GrowthForm]
  numeric_traits: [SLA_mm2_mg, LDMC_mg_g, LeafArea_mm2, SeedMass_mg, Height_cm, WoodDensity_g_cm3]
  log_transform: [SLA_mm2_mg, LeafArea_mm2, SeedMass_mg, Height_cm]
  eive_axes:
    M: { target: EIVE_M, se: EIVE_M_se }
    L: { target: EIVE_L, se: EIVE_L_se }
    N: { target: EIVE_N, se: EIVE_N_se }

model:
  type: elasticnet
  alphas: [0.0001, 0.001, 0.01, 0.1, 1.0, 10.0]
  l1_ratio: [0.1, 0.5, 0.9]

cv:
  n_splits: 5
  group_key: Genus

thresholds:
  init:
    M: [3.5, 6.0]
    L: [4.5, 6.0]
    N: [3.5, 6.0]
  labels:
    M: [dry, mesic, wet]
    L: [shade, semi_shade, open]
    N: [oligotrophic, mesotrophic, eutrophic]

outputs:
  dir: artifacts
  run_prefix: run

