#!/usr/bin/env Rscript
################################################################################
# Master Stage 3 Verification (Bill's Verification)
#
# Purpose: Run all Stage 3 verification checks in sequence
# Orchestrates: CSR calculation, ecosystem services, life form stratification
################################################################################

# ========================================================================
# AUTO-DETECTING PATHS (works on Windows/Linux/Mac, any location)
# ========================================================================
get_repo_root <- function() {
  # First check if environment variable is set (from run_all_bill.R)
  env_root <- Sys.getenv("BILL_REPO_ROOT", unset = NA)
  if (!is.na(env_root) && env_root != "") {
    return(normalizePath(env_root))
  }

  # Otherwise detect from script path
  args <- commandArgs(trailingOnly = FALSE)
  file_arg <- grep("^--file=", args, value = TRUE)
  if (length(file_arg) > 0) {
    script_path <- sub("^--file=", "", file_arg[1])
    # Navigate up from script to repo root
    # Scripts are in src/Stage_X/bill_verification/
    repo_root <- normalizePath(file.path(dirname(script_path), "..", "..", ".."))
  } else {
    # Fallback: assume current directory is repo root
    repo_root <- normalizePath(getwd())
  }
  return(repo_root)
}

repo_root <- get_repo_root()
INPUT_DIR <- file.path(repo_root, "input")
INTERMEDIATE_DIR <- file.path(repo_root, "intermediate")
OUTPUT_DIR <- file.path(repo_root, "output")

# Create output directories
dir.create(file.path(OUTPUT_DIR, "wfo_verification"), recursive = TRUE, showWarnings = FALSE)
dir.create(file.path(OUTPUT_DIR, "stage3"), recursive = TRUE, showWarnings = FALSE)



suppressPackageStartupMessages({
  library(readr)
})

cat(strrep('=', 80), '\n')
cat('STAGE 3 VERIFICATION SUITE\n')
cat(strrep('=', 80), '\n\n')

# Configuration
# Use current R library paths (will inherit from parent session)
R_LIBS <- Sys.getenv('R_LIBS_USER', '')
SCRIPT_DIR <- 'src/Stage_3/bill_verification'
# Input file generated by calculate_csr_bill.R
INPUT_FILE <- file.path(OUTPUT_DIR, "stage3", "bill_with_csr_ecoservices_11711_BILL_VERIFIED.csv")

SCRIPTS <- c(
  'verify_csr_calculation_bill.R',
  'verify_ecoservices_bill.R',
  'verify_lifeform_stratification_bill.R'
)

all_passed <- TRUE

for (i in seq_along(SCRIPTS)) {
  script <- SCRIPTS[i]
  cat(sprintf('[%d/%d] Running %s...\n', i, length(SCRIPTS), script))
  cat(strrep('-', 80), '\n')

  script_path <- file.path(SCRIPT_DIR, script)

  if (!file.exists(script_path)) {
    cat(sprintf('✗ ERROR: Script not found: %s\n\n', script_path))
    all_passed <- FALSE
    next
  }

  # Run script and capture exit status
  result <- system2(
    'env',
    args = c(
      sprintf('R_LIBS_USER=%s', R_LIBS),
      '/usr/bin/Rscript',
      script_path,
      sprintf('--input=%s', INPUT_FILE)
    ),
    stdout = TRUE,
    stderr = TRUE
  )

  exit_code <- attr(result, 'status')
  if (is.null(exit_code)) exit_code <- 0

  # Print output
  cat(paste(result, collapse = '\n'), '\n\n')

  if (exit_code != 0) {
    cat(sprintf('✗ FAILED (exit code: %d)\n\n', exit_code))
    all_passed <- FALSE
  } else {
    cat(sprintf('✓ PASSED\n\n'))
  }
}

# Final summary
cat(strrep('=', 80), '\n')
cat('STAGE 3 VERIFICATION COMPLETE\n')
cat(strrep('=', 80), '\n\n')

if (all_passed) {
  cat('✓ CSR calculation: PASSED\n')
  cat('✓ Ecosystem services: PASSED\n')
  cat('✓ Life form stratification: PASSED\n')
  cat('\nAll verification checks passed.\n')
  quit(status = 0)
} else {
  cat('✗ Some checks failed. Review output above.\n')
  quit(status = 1)
}
