#!/usr/bin/env Rscript
################################################################################
# Master Stage 3 Verification (Bill's Verification)
#
# Purpose: Run all Stage 3 verification checks in sequence
# Orchestrates: CSR calculation, ecosystem services, life form stratification
################################################################################

# ========================================================================
# AUTO-DETECTING PATHS (works on Windows/Linux/Mac, any location)
# ========================================================================
get_repo_root <- function() {
  # First check if environment variable is set (from run_all_bill.R)
  env_root <- Sys.getenv("BILL_REPO_ROOT", unset = NA)
  if (!is.na(env_root) && env_root != "") {
    return(normalizePath(env_root))
  }

  # Otherwise detect from script path
  args <- commandArgs(trailingOnly = FALSE)
  file_arg <- grep("^--file=", args, value = TRUE)
  if (length(file_arg) > 0) {
    script_path <- sub("^--file=", "", file_arg[1])
    # Navigate up from script to repo root
    # Scripts are in src/Stage_X/bill_verification/
    repo_root <- normalizePath(file.path(dirname(script_path), "..", "..", ".."))
  } else {
    # Fallback: assume current directory is repo root
    repo_root <- normalizePath(getwd())
  }
  return(repo_root)
}

repo_root <- get_repo_root()
INPUT_DIR <- file.path(repo_root, "input")
INTERMEDIATE_DIR <- file.path(repo_root, "intermediate")
OUTPUT_DIR <- file.path(repo_root, "output")

# Create output directories
dir.create(file.path(OUTPUT_DIR, "wfo_verification"), recursive = TRUE, showWarnings = FALSE)
dir.create(file.path(OUTPUT_DIR, "stage3"), recursive = TRUE, showWarnings = FALSE)



suppressPackageStartupMessages({
  library(readr)
})

cat(strrep('=', 80), '\n')
cat('STAGE 3 VERIFICATION SUITE\n')
cat(strrep('=', 80), '\n\n')

# ========================================================================
# Configuration: Define verification scripts to run
# ========================================================================
# This master script orchestrates all Stage 3 verification checks
# Each verification script validates a different aspect of the CSR/ecosystem services calculation

# Use current R library paths (will inherit from parent session)
R_LIBS <- Sys.getenv('R_LIBS_USER', '')
# Build absolute path to script directory using repo root
SCRIPT_DIR <- file.path(repo_root, 'src', 'Stage_3', 'bill_verification')

# Input file generated by calculate_csr_bill.R
# This file contains CSR scores + ecosystem service ratings for all species
INPUT_FILE <- file.path(OUTPUT_DIR, "stage3", "bill_with_csr_ecoservices_11711_BILL_VERIFIED.csv")

# Verification scripts to run (in order)
SCRIPTS <- c(
  'verify_csr_calculation_bill.R',        # Check CSR completeness, sum to 100%, ranges
  'verify_ecoservices_bill.R',            # Check ecosystem service patterns
  'verify_lifeform_stratification_bill.R' # Check NPP life form stratification
)

# ========================================================================
# Run all verification scripts sequentially
# ========================================================================
# Track overall pass/fail status
all_passed <- TRUE

for (i in seq_along(SCRIPTS)) {
  script <- SCRIPTS[i]
  cat(sprintf('[%d/%d] Running %s...\n', i, length(SCRIPTS), script))
  cat(strrep('-', 80), '\n')

  script_path <- file.path(SCRIPT_DIR, script)

  # Check if verification script exists
  if (!file.exists(script_path)) {
    cat(sprintf('✗ ERROR: Script not found: %s\n\n', script_path))
    all_passed <- FALSE
    next
  }

  # Run verification script as subprocess and capture output + exit status
  # Use system2() to execute Rscript with environment variables
  # Pass INPUT_FILE as --input argument to each verification script
  result <- system2(
    'env',
    args = c(
      sprintf('R_LIBS_USER=%s', R_LIBS),  # Preserve R library paths (package locations)
      '/usr/bin/Rscript',                  # R interpreter path
      script_path,                         # Verification script to run
      sprintf('--input=%s', INPUT_FILE)   # Pass input file to verification script
    ),
    stdout = TRUE,  # Capture standard output (verification results)
    stderr = TRUE   # Capture error output (any failures)
  )

  # Extract exit code (0 = success, non-zero = failure)
  exit_code <- attr(result, 'status')
  if (is.null(exit_code)) exit_code <- 0

  # Print verification script output
  cat(paste(result, collapse = '\n'), '\n\n')

  # Check if verification passed or failed
  if (exit_code != 0) {
    cat(sprintf('✗ FAILED (exit code: %d)\n\n', exit_code))
    all_passed <- FALSE
  } else {
    cat(sprintf('✓ PASSED\n\n'))
  }
}

# ========================================================================
# Final Summary: Report overall verification status
# ========================================================================
cat(strrep('=', 80), '\n')
cat('STAGE 3 VERIFICATION COMPLETE\n')
cat(strrep('=', 80), '\n\n')

if (all_passed) {
  # All verification checks passed
  cat('✓ CSR calculation: PASSED\n')
  cat('✓ Ecosystem services: PASSED\n')
  cat('✓ Life form stratification: PASSED\n')
  cat('\nAll verification checks passed.\n')
  invisible(TRUE)  # Return success without exiting R session
} else {
  # At least one verification check failed
  cat('✗ Some checks failed. Review output above.\n')
  stop("Verification failed")  # Throw error instead of quitting
}
