$\qquad$
![](https://cdn.mathpix.com/cropped/2025_08_09_4eb14782a91a38fbbf42g-1.jpg?height=170&width=497&top_left_y=1039&top_left_x=4362)

\title{
Ecological Indicator Values for Europe (EIVE): recent developments and performance tests
}

\author{
Jürgen Dengler ${ }^{1^{*}}$, Olha Chusova ${ }^{2}$, Florian Jansen ${ }^{3}$, François Gillet ${ }^{4}$, Christian Berg ${ }^{5}$, Gerhard Karrer ${ }^{6}$, Thomas Raus ${ }^{7}$, Torbjörn Tyler ${ }^{8}$, Severin Aicher ${ }^{1}$, Agnieszka Mankiewicz ${ }^{9}$, Grzegorz Ostrowski9, Stefan Widmer ${ }^{1}$ \& the EIVE Consortium
}
(1) Institute of Natural Resource Sciences (IUNR), Zurich University of Applied Sciences (ZHAW), Wädenswil, Switzerland; (2) National Academy of Science of Ukraine, Kyiv, Ukraine; (3) University of Rostock, Germany; (4) University of Franche-Comté, Besançon, France; (5) Karl-Franzens University of Graz, Austria; (6) BOKU, Vienna, Austria; (7) BGBM, Berlin, Germany; (8) University of Lund, Sweden; (9) University of Warsaw, Poland; *dr.juergen.dengler@gmail.com

Introduction In Europe, ecological indicator values (EIVs) of plants are a very widely and successfully used tool for bioindication. The idea is to combine the expert-based assessment of the niche optima of species along certain niche dimensions, such as soil moisture or pH , and averaging them across all species in a community predicts its position in ecological space. Having been independently "invented" by Heinz Ellenberg and L.G. Ramensky, similar approaches were later implemented in many regions of Europe for various niche dimensions. Meanwhile, there are more than 30 such systems, varying in scaling and taxonomy, thus impeding analyses at a continental scale.
This prompted two author teams in January 2023 to release supra-regional indicator value systems for Europe, the Ellenberg-type indicator values by Tichý et al. (2023: "Tichý") and the Ecological Indicator Values for Europe (EIVE) 1.0 (Dengler et al. 2023; Figs. 1 and 2). While their basic idea is similar, there are many differences in the details (see Box).

\begin{figure}
\includegraphics[width=\textwidth]{https://cdn.mathpix.com/cropped/2025_08_09_4eb14782a91a38fbbf42g-2.jpg?height=1318&width=2744&top_left_y=5172&top_left_x=435}
\captionsetup{labelformat=empty}
\caption{Fig. 1. Spatial coverage of source systems of EIVE 1.0.}
\end{figure}

Fig. 2. Niche position (A) and niche width (B) distribution of the five niche dimensions in EIVE 1.0.

Performance of the two systems we used three regional datasets covering long environmental gradients (one for temperature, two for pH ) with measured environmental variables to compare the relative performance of EIVE 1.0, Tichý et al. (2023) and the two EIV systems valid for Switzerland, "Landolt" and "Ellenberg", and did this with four weighting approaches (Aicher et al. in review). EIVE outperformed all other systems, but particularly "Ellenberg" and "Tichý", while no cover-weighting was better than cover-weighting or sqrt (cover)-weighting. Only inverse niche width, solely available for EIVE and "Landolt", was minimally and nonsignificantly better than no weighting (Fig. 3).

\begin{figure}
\includegraphics[width=\textwidth]{https://cdn.mathpix.com/cropped/2025_08_09_4eb14782a91a38fbbf42g-2.jpg?height=1560&width=4098&top_left_y=9426&top_left_x=797}
\captionsetup{labelformat=empty}
\caption{Fig. 3. Relative performance of four EIV systems and four weighting approaches in predicting measured environmental variables, expressed by Pearson's $r$ in various datasets, tested with mixedeffect models. The points inside the boxes are the arithmetic means. NW = niche width.}
\end{figure}

\section*{References}

Dengler, J., Jansen, F. et al. (2023) Ecological Indicator Values for Europe (EIVE) 1.0. Vegetation Classification and Survey 4: 7-29. https://doi.org/10.3897/VCS.98324.
Tichý et al. (2023) Ellenberg-type indicator values for European vascular plant species. Journal of Vegetation Science 34: e13168.
Aicher et al. (in review) Mean ecological indicator values: use EIVE, but no cover-weighting. Vegetation Classification and Survey.
Chusova et al. (in prep.) Ecological Indicator Values for Europe (EIVE) 1.5: now with bryophytes, lichens and macro-algae.

A EIVE 1.0: niche position (14835 taxa)
![](https://cdn.mathpix.com/cropped/2025_08_09_4eb14782a91a38fbbf42g-2.jpg?height=2140&width=1959&top_left_y=5269&top_left_x=3238)

\begin{tabular}{|l|l|l|l|l|l|}
\hline Taxon group & Vascular plants & Bryophytes & Lichens & Algae & All groups \\
\hline Lines & 99,080 & 12,208 & 4,374 & 77 & 115,739 \\
\hline Matched names & 16,534 & 1,613 & 0 & 0 & 18,147 \\
\hline Non-matched names & 824 & 1,632 & 1,801 & 58 & 4,315 \\
\hline Total names & 17,358 & 3,245 & 1,801 & 58 & 22,462 \\
\hline Mean sources per name & 5.7 & 3.8 & 2.4 & 1.3 & 5.2 \\
\hline Estimated valid taxa & 16,699 & 1,939 & 1,441 & 46 & 20,125 \\
\hline Mean sources per taxon & 5.9 & 6.3 & 3.0 & 1.7 & 5.8 \\
\hline
\end{tabular}

EIVE is a collaborative, community-based endeavor, and we envisage already future development steps:
- EIVE 1.7: addition of further niche dimensions (e.g. salinity, humus content, CSR strategies)
- EIVE 2.0: using the EVA database to recalibrate and expand EIVE
- EIVE 3.0: release of regional/subcontinental EIVE editions

\section*{Conclusions \\ \section*{onclusions}}
- Use EIVE both in regional and continental studies (at least for R and T indicators)
- Don't weight the species by cover, but potentially by inverse niche width
- Join the EIVE consortium if you have ideas for further development or testing

\section*{EIVE 1.0 vs. "Tichý"}
- Based on 31 (EIVE) vs. 12 ("Tichý") source EIV systems
- 5 niche dimensions (EIVE), additionally salinity ("Tichý")
- Uniform scale of 0-10 (EIVE) vs. different scales for each dimension ("Tichý")
- 14,835 (EIVE) vs. 8,679 ("Tichý") accepted taxa
- Covering entire Europe (EIVE) vs. nemoral Europe and Italy ("Tichý")
- Only EIVE has also indicators of niche width

\section*{Future developments of EIVE}

Currently, we are preparing EIVE 1.5 (Chusova et al. in prep.). This version will stay with the same five niche dimensions, but add bryophytes, lichens and algae plus new and updated EIV systems of vascular plants. This version to be released in a few months will increase the EIVE coverage to approx. $\mathbf{2 0 , 0 0 0}$ valid taxa (Table 1).

Table 1. Work status of EIVE 1.5 (as of 10 September 2024).

EIVE is a collaborative, community-based endeavor, EIVE is a collaborative, community-based end
and we envisage already future development steps:
- EIVE 1.7: addition of further niche dimensions (e.g. salinity, humus content, CSR strategies)
- EIVE 2.0: using the EVA database to recalibrate and expand EIVE

EIVE 3.0: release of regional/subcontinental EIVE editions
- Use EIVE both in regional and continental studies (at least for $R$ and $T$ indicators) potentially by inverse niche width further development or testing